language: php

php:
  - 7.2

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('secret') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -psecret
  - sudo service mysql restart
  - mysql -e 'create database tfbb;'

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --force 

scripts:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor